# Copyright (c) 2026 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

# Enable logging
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Enable GPIO for LEDs
CONFIG_GPIO=y

# Enable Axon NPU driver and configure buffer
CONFIG_NRF_AXON=y
CONFIG_NRF_AXON_INTERLAYER_BUFFER_SIZE=229376

# Enable and configure Arducam dependencies (local nordic,arducam-mega driver)
CONFIG_SPI=y
CONFIG_VIDEO=y
CONFIG_VIDEO_ARDUCAM_MEGA=n
CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=2200
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=4

# Other
CONFIG_ASSERT=y
CONFIG_MAIN_STACK_SIZE=2048

# Model postprocessing thresholds
CONFIG_SCORE_THRESHOLD=250
CONFIG_IOU_THRESHOLD=450
