# This is the Jenkins ci variant of the .github/labler.yaml

"__EXCLUDE__":
  - "**/*.md"
  - "**/*.rst"

"CI-test-edge-ai":
  - any:
      - "!.github/**/*"
      - "!doc/**/*"
      - "!.editorconfig"
