# This file configures SonarQube Cloud Automatic Analysis.
# https://sonarcloud.io/project/overview?id=nrfconnect_sdk-edge-ai

# SonarQube Cloud project details
sonar.projectKey=nrfconnect_sdk-edge-ai
sonar.organization=nrfconnect
sonar.projectName=sdk-edge-ai
sonar.projectVersion=1.0

# Path to sources
sonar.sources=.
sonar.exclusions=tests/**/*,**/cmake/**/*,**/doc/**/*,**/generated/**/*,**/nrf_edgeai_generated/**/*,\
  samples/axon/axon_low_power/src/mel_test_vector.*,\
  include/nrf_edgeai/dsp/transform/fft/nrf_dsp_fft_const_tables_*.h,\
  drivers/axon/**/*,\
  include/axon/**/*,\
  include/drivers/axon/**/*,\
  lib/axon/**/*,\
  tools/axon/**/*

# Path to tests
sonar.tests=tests
sonar.test.exclusions=tests/axon/**/*

# Python version (for python projects only)
sonar.python.version=3.12

# Source encoding
sonar.sourceEncoding=UTF-8

# Pull request options
sonar.pullrequest.github.summary_comment=false

# C target configuration
sonar.cfamily.customTargetArch=arm
sonar.cfamily.customTargetVendor=unknown
sonar.cfamily.customTargetSystem=linux
sonar.cfamily.customTargetEnv=gnueabi
