#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

manifest:
  version: "0.13"

  remotes:
    - name: ncs
      url-base: git@github.com:nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.2.0-rc2
      import: true

    - name: axon
      remote: ncs
      repo-path: sdk-axons-ml-lib
      revision: AXONS-ML-RELEASE-0P5P0
      import: false

  self:
    path: edge-ai
