#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

manifest:
  version: "0.13"

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: 0611b5887db87fde99cb7dec1620be5707231ca1
      import: true

    - name: edge-impulse-sdk-zephyr
      url: https://github.com/edgeimpulse/edge-impulse-sdk-zephyr
      path: modules/edge-impulse-sdk-zephyr
      revision: v1.82.3
      west-commands: west/west-commands.yml

  self:
    path: edge-ai
