#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Data forwarder
CONFIG_DATA_FWD_PROTO=y
CONFIG_DATA_FWD_PROTO_CRC=y
CONFIG_DATA_FWD_TRANSPORT_BLE_NUS=y
CONFIG_DATA_FWD_SENSOR_BMI270=y
CONFIG_DATA_FWD_EXTRA_SENSOR_BME688=y

# Select int32 for use with Edge AI Lab
CONFIG_DATA_FWD_PROTO_INT32_VALUES=y

# Data forwarder dependencies
CONFIG_ZCBOR=y
CONFIG_COBS=y
CONFIG_CRC=y

# Sensor dependencies
CONFIG_SENSOR=y
CONFIG_BMI270=y
CONFIG_BME680=y

# Logging and assert
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
CONFIG_ASSERT=y

# BLE NUS transport dependencies
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="nRF DataFwd"
CONFIG_BT_MAX_CONN=1
CONFIG_BT_NUS=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_RX_SIZE=251
