#!/usr/bin/env python3
"""
Copyright (c) 2026 Nordic Semiconductor
SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

Converts test pictures to VWW input format (96x96x3 int8) and emits a C header
so the firmware can run inference on each. Uses tinyml_vww quantization params.
"""
import argparse
import sys
from pathlib import Path

import numpy as np

# tinyml_vww input quantization (from nrf_axon_model_tinyml_vww_.h)
VWW_INPUT_QUANT_MULT = 133693432
VWW_INPUT_QUANT_ROUND = 19
VWW_INPUT_QUANT_ZP = -128
VWW_HEIGHT, VWW_WIDTH, VWW_CHANS = 96, 96, 3
VWW_SIZE = VWW_HEIGHT * VWW_WIDTH * VWW_CHANS


def load_and_quantize(image_path: Path) -> np.ndarray:
    try:
        from PIL import Image
    except ImportError:
        raise RuntimeError("PIL required. Install with: pip install Pillow")
    img = Image.open(image_path)
    if img.mode != "RGB":
        img = img.convert("RGB")
    img = np.array(img, dtype=np.float32) / 255.0
    if img.shape[0] != VWW_HEIGHT or img.shape[1] != VWW_WIDTH:
        pil_img = Image.fromarray((img * 255).astype(np.uint8))
        pil_img = pil_img.resize((VWW_WIDTH, VWW_HEIGHT), Image.Resampling.BILINEAR)
        img = np.array(pil_img, dtype=np.float32) / 255.0
    # int8 = (float * quant_mult) >> quant_round + quant_zp, clamp to [-128, 127]
    q = (img * VWW_INPUT_QUANT_MULT).astype(np.int64)
    q = (q >> VWW_INPUT_QUANT_ROUND) + VWW_INPUT_QUANT_ZP
    q = np.clip(q, -128, 127).astype(np.int8)
    # VWW expects CHW (channel, height, width); PIL gives HWC
    q = np.transpose(q, (2, 0, 1))
    return q


def array_to_c(name: str, arr: np.ndarray) -> str:
    flat = arr.flatten()
    lines = ["static const int8_t " + name + "[" + str(len(flat)) + "] = {"]
    for i in range(0, len(flat), 16):
        chunk = flat[i : i + 16]
        lines.append("  " + ", ".join(str(int(x)) for x in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Convert test pictures to VWW C header")
    ap.add_argument(
        "--pictures-dir",
        default="pictures",
        help="Directory containing demo_picture.jpeg, demo_2.jpeg, demo_3.jpeg",
    )
    ap.add_argument(
        "--out",
        default="src/generated/test_images.h",
        help="Output header path (default: src/generated/test_images.h)",
    )
    args = ap.parse_args()
    root = Path(__file__).resolve().parent.parent
    pics_dir = root / args.pictures_dir
    out_path = root / args.out

    images = [
        ("demo_picture", "demo_picture.jpeg"),
        ("demo_2", "demo_2.jpeg"),
        ("demo_3", "demo_3.jpeg"),
    ]
    arrays = []
    for var_name, filename in images:
        path = pics_dir / filename
        if not path.is_file():
            print(f"Error: image not found: {path}", file=sys.stderr)
            return 1
        arr = load_and_quantize(path)
        arrays.append((var_name, arr))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        "/* Auto-generated by scripts/embed_test_images.py */",
        "#ifndef PERSON_RECOGNITION_TEST_IMAGES_H",
        "#define PERSON_RECOGNITION_TEST_IMAGES_H",
        "",
        "#include <stdint.h>",
        "",
        "#define PERSON_RECOGNITION_NUM_TEST_IMAGES 3",
        "",
    ]
    for var_name, arr in arrays:
        parts.append(array_to_c("test_image_" + var_name, arr))
        parts.append("")
    parts.append("static const int8_t *const person_recognition_test_inputs[] = {")
    for var_name, _ in arrays:
        parts.append("  test_image_" + var_name + ",")
    parts.append("};")
    parts.append("")
    parts.append('static const char *const person_recognition_test_names[] = {')
    for var_name, _ in arrays:
        parts.append('  "' + var_name + '",')
    parts.append("};")
    parts.append("")
    parts.append("#endif /* PERSON_RECOGNITION_TEST_IMAGES_H */")
    out_path.write_text("\n".join(parts))
    print(f"Wrote {out_path} ({len(arrays)} images)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
