/*
 * Copyright (c) 2024, Nordic Semiconductor ASA. All Rights Reserved.
 *
 * The information contained herein is confidential property of Nordic Semiconductor ASA.
 * The use, copying, transfer or disclosure of such information is prohibited except by
 * express written agreement with Nordic Semiconductor ASA.
 */

 /**
  * These APIs support test inference on axon neural network models. 
  * They are used in the test_nn_inference application, as well as by private Nordic Semiconducotr test code.
  * 
  * 
  */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdarg.h>
#include <stdint.h>
#include "nrf_axon_driver.h"
#include "nrf_axon_nn_infer.h"

/**
 * Test extensions to nrf_axon_nn_compiled_model_test_s to support 
 * model layer testing. Each compiled layer model instance produced by the compiler is an 
 * instance of nrf_axon_nn_compiled_model_layer_s.
 */
typedef struct {
  nrf_axon_nn_compiled_model_s base;  /**< base compiled model information. */
  uint8_t layer_ndx;                  /**< Index into the model of this layer. Used to dereference the layer_expected_output_vectors by the test framework. */
  int8_t input0_layer_ndx;            /**< Index into the model of the layer that is input0 to this model. Used to dereference the layer_expected_output_vectors by the test framework. */
  int8_t input1_layer_ndx;            /**< Index into the model of the layer that is input0 to this model. Used to dereference the layer_expected_output_vectors by the test framework. */
} nrf_axon_nn_compiled_model_layer_s;

/**
 * Collection of the various test vector structures generated by the nn
 * compiler. 
 * Populate it using nrf_axon_nn_populate_model_test_info_s
 */
typedef struct {
  const char* test_name;                              /**< name that gets printed with the test. */
  const int8_t** full_model_input_vectors;            /**< 1 or more fully model input test vectors */
  const int8_t** full_model_expected_output_vectors;  /**< full model expected output vectors, one for each full model input vector */
  uint16_t full_model_vector_count;                   /**< number of full model test/expected_output vector pairs. */
  const int8_t** layer_vectors;                       /**< individual layer vectors. These serve as both input and expected output. */
  uint16_t layer_cnt;                                 /**< number of elements in layer_models and layer_vectors */
} nrf_axon_nn_model_test_info_s;

/**
 * @brief Populates a nrf_axon_nn_model_test_info_s instance with the provided data.
 * 
 * @param[in] the_struct Instance of nrf_axon_nn_model_test_info_s to populate.
 * See nrf_axon_nn_model_test_info_s for a description of the remaining data elements.
 */
void nrf_axon_nn_populate_model_test_info_s(
  nrf_axon_nn_model_test_info_s *the_struct,
  const char* test_name,
  const int8_t** full_model_input_vectors,
  const int8_t** full_model_expected_output_vectors,
  uint16_t full_model_vector_count,
  const int8_t** layer_vectors,
  uint16_t layer_cnt);

/**
 * @brief Run the inference test vectors for the passed models.
 * 
 * This function supports running inference test vectors as well as optional layer test
 * vectors on a list of models.
 * 
 * @param[in] compiled_full_models List of compiled models to run test inference for.
 * @param[in] test_group_name Name of the collective set of tests. Printed at the start and end of the test. 
 * @param[in] models_count Number of elements in *compiled_full_models.
 * @param[in] compiled_1_layer_models Optional. If not null, the list of layer models for each corresponding model in compiled_full_models.
 * @param[in] model_layers_count List of layer counts for each entry in compiled_1_layer_models.
 * @param[in] test_vectors List of test vector structs for each model in compiled_full_models.
 */
int nrf_axon_nn_run_test_vectors(const nrf_axon_nn_compiled_model_s **compiled_full_models,
      const char* test_group_name, uint16_t models_count,
      const nrf_axon_nn_compiled_model_layer_s **compiled_1_layer_models[],
      uint16_t *model_layers_count,
      const nrf_axon_nn_model_test_info_s *test_vectors);

/**
 * @brief Prints formatted test result.
 * 
 * Used internally by the driver and some test apps.
 */
int nrf_axon_print_test_inference_results(const nrf_axon_nn_compiled_model_s *compiled_model, int8_t *output_ptr, uint32_t profiling_ticks);
#ifdef __cplusplus
} // extern "C" {
#endif

