# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

if(NOT DEFINED MODEL_IMAGE_C OR NOT DEFINED MODEL_IMAGE_O OR NOT DEFINED MODEL_IMAGE_ELF
   OR NOT DEFINED MODEL_IMAGE_BIN OR NOT DEFINED SYMS_HEADER
   OR NOT DEFINED MODEL_PARTITION_ADDR OR NOT DEFINED LINKER_SCRIPT
   OR NOT DEFINED INCLUDE_DIR_PARTITION OR NOT DEFINED INCLUDE_DIR_EDGE_AI
   OR NOT DEFINED CMAKE_C_COMPILER OR NOT DEFINED CMAKE_OBJCOPY)
  message(FATAL_ERROR "build_model_image.cmake: missing required variables")
endif()

execute_process(
  COMMAND ${CMAKE_C_COMPILER}
    -c ${MODEL_IMAGE_C}
    -o ${MODEL_IMAGE_O}
    -I${INCLUDE_DIR_PARTITION}
    -I${INCLUDE_DIR_EDGE_AI}
    -include ${SYMS_HEADER}
    -DNRF_AXON_MODEL_PARTITION_ADDR=${MODEL_PARTITION_ADDR}
  COMMAND_ERROR_IS_FATAL ANY
)

execute_process(
  COMMAND ${CMAKE_C_COMPILER}
    -nostdlib
    -nostartfiles
    -Wl,--gc-sections
    -Wl,--defsym=NRF_AXON_MODEL_PARTITION_ADDR=${MODEL_PARTITION_ADDR}
    -T ${LINKER_SCRIPT}
    -o ${MODEL_IMAGE_ELF}
    ${MODEL_IMAGE_O}
  COMMAND_ERROR_IS_FATAL ANY
)

execute_process(
  COMMAND ${CMAKE_OBJCOPY}
    -O binary
    -j .model_image
    ${MODEL_IMAGE_ELF}
    ${MODEL_IMAGE_BIN}
  COMMAND_ERROR_IS_FATAL ANY
)
