#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_NCS_SAMPLES_DEFAULTS=y

# nRF Edge AI
CONFIG_NRF_EDGEAI=y
# nRF Edge AI dependencies
CONFIG_NEWLIB_LIBC=y
CONFIG_FPU=y

# temporary directly use sdk-axons-ml-lib
CONFIG_NRF_AXON=y
CONFIG_NRF_AXON_INTERLAYER_BUFFER_SIZE=16

