#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_NRF_AXON=y
CONFIG_NRF_AXON_INTERLAYER_BUFFER_SIZE=36

# Use model that is dedicated for Axon NPU
CONFIG_NRF_AXON_MODEL_NAME="ei_model_nrf_accel_sim_54"
CONFIG_EDGE_IMPULSE_PATH="ei_model_nrf_accel_sim_axon_v54.zip"
