#!/usr/bin/env python3
"""
Copyright (c) 2026 Nordic Semiconductor
SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

Resize demo_picture.jpeg on PC to the person_det Axon input (128x160 RGB, CHW int8),
using the same preprocessing as device: (pixel/255)*2-1 then Axon quant from header.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import numpy as np


def parse_axon_input_from_header(header_path: Path, model_symbol: str) -> dict:
    text = header_path.read_text(encoding="utf-8", errors="replace")
    anchor = f"const nrf_axon_nn_compiled_model_s {model_symbol}"
    idx = text.find(anchor)
    if idx < 0:
        raise ValueError(f"Could not find '{anchor}' in {header_path}")
    chunk = text[idx : idx + 12000]
    dim_m = re.search(
        r"\.dimensions\s*=\s*\{\s*"
        r"\.height\s*=\s*(\d+),\s*"
        r"\.width\s*=\s*(\d+),\s*"
        r"\.channel_cnt\s*=\s*(\d+),",
        chunk,
        re.DOTALL,
    )
    if not dim_m:
        raise ValueError(f"Could not parse .dimensions in {header_path}")
    height, width, chans = (int(dim_m.group(1)), int(dim_m.group(2)), int(dim_m.group(3)))
    qm_m = re.search(r"\.quant_mult\s*=\s*(\d+),", chunk)
    qr_m = re.search(r"\.quant_round\s*=\s*(\d+),", chunk)
    zp_m = re.search(r"\.quant_zp\s*=\s*(-?\d+),", chunk)
    st_m = re.search(r"\.stride\s*=\s*(\d+),", chunk)
    if not all([qm_m, qr_m, zp_m, st_m]):
        raise ValueError(f"Could not parse quant/stride in {header_path}")
    stride = int(st_m.group(1))
    if stride == width:
        use_chw = True
    elif stride == width * chans:
        use_chw = False
    else:
        use_chw = True
    return {
        "height": height,
        "width": width,
        "channel_cnt": chans,
        "quant_mult": int(qm_m.group(1)),
        "quant_round": int(qr_m.group(1)),
        "quant_zp": int(zp_m.group(1)),
        "use_chw": use_chw,
    }


def load_jpeg_quantized(
    image_path: Path,
    height: int,
    width: int,
    use_chw: bool,
    quant_mult: int,
    quant_round: int,
    quant_zp: int,
) -> np.ndarray:
    try:
        from PIL import Image
    except ImportError as e:
        raise RuntimeError("Pillow required: pip install Pillow") from e

    img = Image.open(image_path)
    if img.mode != "RGB":
        img = img.convert("RGB")
    # PIL resize: (width, height)
    img = img.resize((width, height), Image.Resampling.BILINEAR)
    x = np.array(img, dtype=np.float32) / 255.0
    x = x * 2.0 - 1.0
    q = (x * quant_mult).astype(np.int64)
    q = (q >> quant_round) + quant_zp
    q = np.clip(q, -128, 127).astype(np.int8)
    if use_chw:
        q = np.transpose(q, (2, 0, 1))
    return q


def array_to_c(name: str, arr: np.ndarray) -> str:
    flat = arr.flatten()
    lines = [f"static const int8_t {name}[{len(flat)}] = {{"]
    for i in range(0, len(flat), 16):
        chunk = flat[i : i + 16]
        lines.append("  " + ", ".join(str(int(x)) for x in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Embed person_det demo input as C header")
    ap.add_argument("--axon-header", required=True, type=Path, help="nrf_axon_model_person_det_.h")
    ap.add_argument("--model-symbol", default="model_person_det")
    ap.add_argument("--jpeg", required=True, type=Path, help="Input JPEG (e.g. demo_picture.jpeg)")
    ap.add_argument("--out", required=True, type=Path, help="Output header path")
    args = ap.parse_args()

    if not args.axon_header.is_file():
        print(f"Error: header not found: {args.axon_header}", file=sys.stderr)
        return 1
    if not args.jpeg.is_file():
        print(f"Error: JPEG not found: {args.jpeg}", file=sys.stderr)
        return 1

    try:
        spec = parse_axon_input_from_header(args.axon_header, args.model_symbol)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    h, w = spec["height"], spec["width"]
    arr = load_jpeg_quantized(
        args.jpeg,
        h,
        w,
        spec["use_chw"],
        spec["quant_mult"],
        spec["quant_round"],
        spec["quant_zp"],
    )
    nbytes = int(arr.size)
    if nbytes != h * w * spec["channel_cnt"]:
        print(f"Error: tensor size mismatch {nbytes} vs {h}*{w}*3", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(
        [
            "/* Auto-generated by scripts/embed_demo_input.py - do not edit */",
            "#ifndef PERSON_DET_DEMO_INPUT_H",
            "#define PERSON_DET_DEMO_INPUT_H",
            "",
            "#include <stdint.h>",
            "",
            f"#define PERSON_DET_DEMO_INPUT_BYTES ({nbytes})",
            "",
            array_to_c("person_det_demo_input", arr),
            "",
            "#endif /* PERSON_DET_DEMO_INPUT_H */",
            "",
        ]
    )
    args.out.write_text(body, encoding="utf-8")
    print(f"Wrote {args.out} ({nbytes} bytes from {args.jpeg.name}, {w}x{h})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
