# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Second-stage compile/link script for Axon model partition images.
# Invoked from model_ota_axon_image.cmake after zephyr.elf exists.

if(NOT DEFINED MODEL_IMAGE_STUB_C OR NOT DEFINED MODEL_HEADER_DIR
   OR NOT DEFINED MODEL_IMAGE_HEADER OR NOT DEFINED MODEL_IMAGE_MODEL_SYM
   OR NOT DEFINED MODEL_IMAGE_O OR NOT DEFINED MODEL_IMAGE_ELF
   OR NOT DEFINED MODEL_IMAGE_BIN_RAW OR NOT DEFINED MODEL_IMAGE_BIN
   OR NOT DEFINED SYMS_LINKER_SCRIPT OR NOT DEFINED MODEL_PARTITION_ADDR
   OR NOT DEFINED LINKER_SCRIPT OR NOT DEFINED CMAKE_C_COMPILER
   OR NOT DEFINED CMAKE_OBJCOPY OR NOT DEFINED CMAKE_NM
   OR NOT DEFINED CRC_TOOL OR NOT DEFINED VALIDATE_TOOL
   OR NOT DEFINED DEFS_HEADER OR NOT DEFINED PYTHON_EXECUTABLE
   OR NOT DEFINED MODEL_IMAGE_NAME_STR OR NOT DEFINED MODEL_IMAGE_VERSION_U32
   OR NOT DEFINED INCLUDE_DIR_EDGE_AI OR NOT DEFINED ZEPHYR_BASE
   OR NOT DEFINED ZEPHYR_BUILD_DIR)
  message(FATAL_ERROR "build_model_image_axon.cmake: missing required variables")
endif()

set(MODEL_IMAGE_HEADER_C "\"${MODEL_IMAGE_HEADER}\"")
set(MODEL_IMAGE_NAME_STR_C "\"${MODEL_IMAGE_NAME_STR}\"")

set(model_image_compile_flags
  -I${MODEL_HEADER_DIR}
  -I${INCLUDE_DIR_EDGE_AI}
  -I${ZEPHYR_BASE}/include
  -I${ZEPHYR_BUILD_DIR}/zephyr/include/generated
  -include ${ZEPHYR_BUILD_DIR}/zephyr/include/generated/zephyr/autoconf.h
  -DMODEL_OTA_AXON_IMAGE
  -DMODEL_IMAGE_HEADER=${MODEL_IMAGE_HEADER_C}
  -DMODEL_IMAGE_MODEL_SYM=${MODEL_IMAGE_MODEL_SYM}
  -DMODEL_IMAGE_NAME_STR=${MODEL_IMAGE_NAME_STR_C}
  -DMODEL_IMAGE_VERSION_U32=${MODEL_IMAGE_VERSION_U32}u
)

if(DEFINED NRF_AXON_INTERLAYER_BUFFER_SIZE)
  list(APPEND model_image_compile_flags
    -DNRF_AXON_INTERLAYER_BUFFER_SIZE=${NRF_AXON_INTERLAYER_BUFFER_SIZE})
endif()

execute_process(
  COMMAND ${CMAKE_C_COMPILER}
    -c ${MODEL_IMAGE_STUB_C}
    -o ${MODEL_IMAGE_O}
    -DNRF_MODEL_PARTITION_ADDR=${MODEL_PARTITION_ADDR}
    ${model_image_compile_flags}
  COMMAND_ERROR_IS_FATAL ANY
)

execute_process(
  COMMAND ${CMAKE_C_COMPILER}
    -nostdlib
    -nostartfiles
    -Wl,--gc-sections
    -Wl,--defsym=NRF_MODEL_PARTITION_ADDR=${MODEL_PARTITION_ADDR}
    -T ${LINKER_SCRIPT}
    -T ${SYMS_LINKER_SCRIPT}
    -o ${MODEL_IMAGE_ELF}
    ${MODEL_IMAGE_O}
  COMMAND_ERROR_IS_FATAL ANY
)

execute_process(
  COMMAND ${CMAKE_OBJCOPY}
    -O binary
    -j .model_image
    ${MODEL_IMAGE_ELF}
    ${MODEL_IMAGE_BIN_RAW}
  COMMAND_ERROR_IS_FATAL ANY
)

execute_process(
  COMMAND ${PYTHON_EXECUTABLE} ${CRC_TOOL} --bin ${MODEL_IMAGE_BIN_RAW} -o ${MODEL_IMAGE_BIN}
  COMMAND_ERROR_IS_FATAL ANY
)

execute_process(
  COMMAND ${PYTHON_EXECUTABLE} ${VALIDATE_TOOL}
    --nm ${CMAKE_NM}
    --elf ${MODEL_IMAGE_ELF}
    --bin ${MODEL_IMAGE_BIN}
    --partition-addr ${MODEL_PARTITION_ADDR}
    --defs-header ${DEFS_HEADER}
    --model-symbol ${MODEL_IMAGE_MODEL_SYM}
  COMMAND_ERROR_IS_FATAL ANY
)
