#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# CMake helper for the Neuton model-only OTA PoC: per-model static library + payload discard.
#
# model_ota_neuton_wire(SOLUTION_ID <id> MODEL_SRC <abs-path-to-nrf_edgeai_user_model.c>
#                       [LIB_NAME <static-lib-target>])
#
# For each OTA-updatable model:
#
#   1. Builds a dedicated static library (default target ota_neuton_<SOLUTION_ID>) containing
#      only that model's generated nrf_edgeai_user_model.c, and links it into the app. Models
#      that stay compiled into the app target directly are unaffected and keep their payload
#      in flash (non-updatable / baked-in models).
#
#   2. Compiles the library with -ffunction-sections -fdata-sections so each file-static payload
#      array lands in its own input section (.rodata.MODEL_WEIGHTS, ...).
#
#   3. Appends archive-scoped /DISCARD/ rules for *that* library only:
#        *libota_neuton_<id>.a:*(.rodata.MODEL_WEIGHTS)
#      GNU ld's archive+section selector drops payload rodata from wired models individually,
#      without touching identically named sections in other archives or in libapp.a.
#
# The model source itself is not edited: the same arrays compile in both the app-side library
# (OTA path, payload discarded) and the partition-image stub (CONFIG_MODEL_OTA_NEUTON undefined,
# payload kept for the linked image).

include_guard(GLOBAL)

set(MODEL_OTA_NEUTON_PAYLOAD_SECTIONS
    .rodata.MODEL_WEIGHTS
    .rodata.MODEL_NEURON_ACTIVATION_WEIGHTS
    .rodata.MODEL_NEURON_ACTIVATION_TYPE_MASK
    .rodata.MODEL_NEURONS_LINKS
    .rodata.MODEL_NEURON_INTERNAL_LINKS_NUM
    .rodata.MODEL_NEURON_EXTERNAL_LINKS_NUM
    .rodata.MODEL_OUTPUT_NEURONS_INDICES
    .rodata.MODEL_OUTPUT_SCALE_MIN
    .rodata.MODEL_OUTPUT_SCALE_MAX
    .rodata.MODEL_AVERAGE_EMBEDDING
)

function(model_ota_neuton_regenerate_discard_fragment)
  set(frag "${CMAKE_CURRENT_BINARY_DIR}/model_ota_neuton_discard.ld")

  get_property(wired GLOBAL PROPERTY model_ota_neuton_wired)
  string(REPLACE ";" "\n *   " wired_comment "${wired}")

  get_property(discard_lines GLOBAL PROPERTY model_ota_neuton_discard_lines)
  string(REPLACE ";" "\n" discard_body "${discard_lines}")

  file(WRITE ${frag}
"/* Auto-generated by model_ota_neuton_wire(); do not edit.
 * Drops payload rodata from each OTA-wired model static library only (archive-scoped rules).
 * Placed via ROM_SECTIONS (before the generic rodata collector) so GNU ld's first-match rule
 * routes matching sections here. Non-wired models compiled into the app keep their payload.
 * OTA-wired model(s):
 *   ${wired_comment}
 */
/DISCARD/ :
{
${discard_body}
}
")

  get_property(registered GLOBAL PROPERTY model_ota_neuton_discard_registered)
  if(NOT registered)
    set_property(GLOBAL PROPERTY model_ota_neuton_discard_registered TRUE)
    zephyr_linker_sources(ROM_SECTIONS ${frag})
  endif()
endfunction()

function(model_ota_neuton_wire)
  cmake_parse_arguments(MO "" "SOLUTION_ID;MODEL_SRC;LIB_NAME" "" ${ARGN})

  if(NOT MO_MODEL_SRC)
    message(FATAL_ERROR "model_ota_neuton_wire: MODEL_SRC is required")
  endif()
  if(NOT MO_SOLUTION_ID)
    message(FATAL_ERROR "model_ota_neuton_wire: SOLUTION_ID is required")
  endif()
  if(NOT MO_LIB_NAME)
    set(MO_LIB_NAME ota_neuton_${MO_SOLUTION_ID})
  endif()

  get_filename_component(model_dir ${MO_MODEL_SRC} DIRECTORY)

  if(TARGET ${MO_LIB_NAME})
    message(FATAL_ERROR "model_ota_neuton_wire: duplicate LIB_NAME/target ${MO_LIB_NAME}")
  endif()

  add_library(${MO_LIB_NAME} STATIC ${MO_MODEL_SRC})
  target_link_libraries(${MO_LIB_NAME} PRIVATE zephyr_interface zephyr_generated_headers)
  target_include_directories(${MO_LIB_NAME} PRIVATE
                             ${model_dir}
                             $<TARGET_PROPERTY:app,INCLUDE_DIRECTORIES>)
  target_compile_options(${MO_LIB_NAME} PRIVATE -ffunction-sections -fdata-sections)
  target_link_libraries(app PRIVATE ${MO_LIB_NAME})

  set(archive_glob "*lib${MO_LIB_NAME}.a")
  foreach(section ${MODEL_OTA_NEUTON_PAYLOAD_SECTIONS})
    set_property(GLOBAL APPEND PROPERTY model_ota_neuton_discard_lines
                 "\t${archive_glob}:*(${section})")
  endforeach()

  set_property(GLOBAL APPEND PROPERTY model_ota_neuton_wired
               "solution ${MO_SOLUTION_ID} (${MO_LIB_NAME}) <- ${MO_MODEL_SRC}")

  model_ota_neuton_regenerate_discard_fragment()
endfunction()
