#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# CMake helper for the Neuton model-only OTA PoC: per-model static library + payload discard.
#
# model_ota_neuton_wire(SOLUTION_ID <id> MODEL_SRC <abs-path-to-nrf_edgeai_user_model.c>
#                       MAX_NEURONS <cap> [LIB_NAME <static-lib-target>])
#
# For each OTA-updatable model:
#
#   1. Builds a dedicated static library (default target ota_neuton_<SOLUTION_ID>) from
#      lib/model_ota/src/model_ota_neuton_app_stub.c with MODEL_OTA_NEUTON_WIRED and a per-model
#      MODEL_OTA_NEUTON_MAX_NEURONS. Models compiled directly into the app are unaffected
#      and keep compile-time descriptors and payload.
#
#   2. Compiles with -ffunction-sections -fdata-sections so payload arrays land in named
#      input sections (.rodata.MODEL_WEIGHTS, ...).
#
#   3. Appends archive-scoped /DISCARD/ rules for *that* library only.
#
# Partition images use lib/model_ota/src/model_ota_neuton_image_stub.c instead (compile-time
# descriptor + payload kept for the linked image).

include_guard(GLOBAL)

get_filename_component(MODEL_OTA_ROOT ${CMAKE_CURRENT_LIST_DIR}/.. ABSOLUTE)

set(MODEL_OTA_NEUTON_PAYLOAD_SECTIONS
    .rodata.MODEL_WEIGHTS
    .rodata.MODEL_NEURON_ACTIVATION_WEIGHTS
    .rodata.MODEL_NEURON_ACTIVATION_TYPE_MASK
    .rodata.MODEL_NEURONS_LINKS
    .rodata.MODEL_NEURON_INTERNAL_LINKS_NUM
    .rodata.MODEL_NEURON_EXTERNAL_LINKS_NUM
    .rodata.MODEL_OUTPUT_NEURONS_INDICES
    .rodata.MODEL_OUTPUT_SCALE_MIN
    .rodata.MODEL_OUTPUT_SCALE_MAX
    .rodata.MODEL_AVERAGE_EMBEDDING
)

function(model_ota_neuton_regenerate_discard_fragment)
  set(frag "${CMAKE_CURRENT_BINARY_DIR}/model_ota_neuton_discard.ld")

  get_property(wired GLOBAL PROPERTY model_ota_neuton_wired)
  string(REPLACE ";" "\n *   " wired_comment "${wired}")

  get_property(discard_lines GLOBAL PROPERTY model_ota_neuton_discard_lines)
  string(REPLACE ";" "\n" discard_body "${discard_lines}")

  file(WRITE ${frag}
"/* Auto-generated by model_ota_neuton_wire(); do not edit.
 * Drops payload rodata from each OTA-wired model static library only (archive-scoped rules).
 * Placed via ROM_SECTIONS (before the generic rodata collector) so GNU ld's first-match rule
 * routes matching sections here. Non-wired models compiled into the app keep their payload.
 * OTA-wired model(s):
 *   ${wired_comment}
 */
/DISCARD/ :
{
${discard_body}
}
")

  get_property(registered GLOBAL PROPERTY model_ota_neuton_discard_registered)
  if(NOT registered)
    set_property(GLOBAL PROPERTY model_ota_neuton_discard_registered TRUE)
    zephyr_linker_sources(ROM_SECTIONS ${frag})
  endif()
endfunction()

function(model_ota_neuton_wire)
  cmake_parse_arguments(MO "" "SOLUTION_ID;MODEL_SRC;LIB_NAME;MAX_NEURONS" "" ${ARGN})

  if(NOT MO_MODEL_SRC)
    message(FATAL_ERROR "model_ota_neuton_wire: MODEL_SRC is required")
  endif()
  if(NOT MO_SOLUTION_ID)
    message(FATAL_ERROR "model_ota_neuton_wire: SOLUTION_ID is required")
  endif()
  if(NOT MO_MAX_NEURONS)
    message(FATAL_ERROR "model_ota_neuton_wire: MAX_NEURONS is required")
  endif()
  if(NOT MO_LIB_NAME)
    set(MO_LIB_NAME ota_neuton_${MO_SOLUTION_ID})
  endif()

  get_filename_component(model_dir ${MO_MODEL_SRC} DIRECTORY)
  get_filename_component(model_basename ${MO_MODEL_SRC} NAME)
  set(stub_src ${MODEL_OTA_ROOT}/src/model_ota_neuton_app_stub.c)

  if(TARGET ${MO_LIB_NAME})
    message(FATAL_ERROR "model_ota_neuton_wire: duplicate LIB_NAME/target ${MO_LIB_NAME}")
  endif()

  add_library(${MO_LIB_NAME} STATIC ${stub_src})
  target_link_libraries(${MO_LIB_NAME} PRIVATE zephyr_interface)
  add_dependencies(${MO_LIB_NAME} zephyr_generated_headers)
  target_include_directories(${MO_LIB_NAME} PRIVATE ${model_dir})
  target_compile_options(${MO_LIB_NAME} PRIVATE -ffunction-sections -fdata-sections)
  target_compile_definitions(${MO_LIB_NAME} PRIVATE
                             MODEL_OTA_NEUTON_WIRED=1
                             MODEL_OTA_NEUTON_MODEL_SRC=${model_basename}
                             MODEL_OTA_NEUTON_MAX_NEURONS=${MO_MAX_NEURONS})
  set_source_files_properties(${stub_src}
                              TARGET_DIRECTORY ${MO_LIB_NAME}
                              PROPERTIES OBJECT_DEPENDS "${MO_MODEL_SRC}")
  target_link_libraries(app PRIVATE ${MO_LIB_NAME})

  set(archive_glob "*lib${MO_LIB_NAME}.a")
  foreach(section ${MODEL_OTA_NEUTON_PAYLOAD_SECTIONS})
    set_property(GLOBAL APPEND PROPERTY model_ota_neuton_discard_lines
                 "\t${archive_glob}:*(${section})")
  endforeach()

  set_property(GLOBAL APPEND PROPERTY model_ota_neuton_wired
               "solution ${MO_SOLUTION_ID} (${MO_LIB_NAME}, max_neurons=${MO_MAX_NEURONS}) <- ${MO_MODEL_SRC}")

  model_ota_neuton_regenerate_discard_fragment()
endfunction()
