#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Shared helpers for model_ota Neuton/Axon partition-image builds.

include_guard(GLOBAL)

# Pack "x.y.z" into major<<16 | minor<<8 | patch for @ref model_image_header.model_version.
function(model_ota_pack_version version_str out_var)
  string(REPLACE "." ";" ver_parts "${version_str}")
  list(LENGTH ver_parts ver_len)
  list(GET ver_parts 0 ver_major)
  set(ver_minor 0)
  set(ver_patch 0)
  if(ver_len GREATER 1)
    list(GET ver_parts 1 ver_minor)
  endif()
  if(ver_len GREATER 2)
    list(GET ver_parts 2 ver_patch)
  endif()
  math(EXPR ver_u32 "(${ver_major} << 16) | (${ver_minor} << 8) | ${ver_patch}")
  set(${out_var} ${ver_u32} PARENT_SCOPE)
endfunction()

# The nrf_edgeai_t parameter arrays a model image carries in its edgeai_params block. An OTA-wired
# solution initializes them from the image instead (MODEL_OTA_WIRED zeroes the generated
# initializers), so they are unreferenced in the app and can be dropped from its library.
set(MODEL_OTA_EDGEAI_PARAM_SECTIONS
    .rodata.INPUT_FEATURES_SCALE_MIN
    .rodata.INPUT_FEATURES_SCALE_MAX
    .rodata.EXTRACTED_FEATURES_SCALE_MIN
    .rodata.EXTRACTED_FEATURES_SCALE_MAX
    .rodata.FEATURES_EXTRACTION_ARGUMENTS
    .rodata.MODEL_OUTPUT_SCALE_MIN
    .rodata.MODEL_OUTPUT_SCALE_MAX
    .rodata.MODEL_AVERAGE_EMBEDDING
)

function(model_ota_regenerate_discard_fragment)
  set(frag "${CMAKE_CURRENT_BINARY_DIR}/model_ota_discard.ld")

  get_property(wired GLOBAL PROPERTY model_ota_discard_wired)
  string(REPLACE ";" "\n *   " wired_comment "${wired}")

  get_property(discard_lines GLOBAL PROPERTY model_ota_discard_lines)
  string(REPLACE ";" "\n" discard_body "${discard_lines}")

  file(WRITE ${frag}
"/* Auto-generated by model_ota_discard_register(); do not edit.
 * Drops payload rodata from each OTA-wired model static library only (archive-scoped rules).
 * Placed via ROM_SECTIONS (before the generic rodata collector) so GNU ld's first-match rule
 * routes matching sections here. Non-wired models compiled into the app keep their payload.
 * OTA-wired model(s):
 *   ${wired_comment}
 */
/DISCARD/ :
{
${discard_body}
}
")

  get_property(registered GLOBAL PROPERTY model_ota_discard_registered)
  if(NOT registered)
    set_property(GLOBAL PROPERTY model_ota_discard_registered TRUE)
    zephyr_linker_sources(ROM_SECTIONS ${frag})
  endif()
endfunction()

# Drop the given input sections from one OTA-wired model static library.
#
# model_ota_discard_register(LIB <static-lib-target> DESCRIPTION <str> SECTIONS <section>...)
#
# The library must be compiled with -ffunction-sections -fdata-sections so each array lands in
# its own named input section.
function(model_ota_discard_register)
  cmake_parse_arguments(MD "" "LIB;DESCRIPTION" "SECTIONS" ${ARGN})

  if(NOT MD_LIB OR NOT MD_SECTIONS)
    message(FATAL_ERROR "model_ota_discard_register requires LIB and SECTIONS")
  endif()

  target_compile_options(${MD_LIB} PRIVATE -ffunction-sections -fdata-sections)

  set(archive_glob "*lib${MD_LIB}.a")
  foreach(section ${MD_SECTIONS})
    set_property(GLOBAL APPEND PROPERTY model_ota_discard_lines
                 "\t${archive_glob}:*(${section})")
  endforeach()
  set_property(GLOBAL APPEND PROPERTY model_ota_discard_wired "${MD_DESCRIPTION}")

  model_ota_regenerate_discard_fragment()
endfunction()
